# SOPS configuration for encrypting Kubernetes secrets
creation_rules:
  - path_regex: .demo/manifests/apps/.*/.*secret.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age17y5km0zn84um7vgk5jrh0k5c3ddaud3zfrgcq5tvyrr2gt6rgpfs7hrwrw
  - path_regex: .demo/manifests/apps/.*/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age17y5km0zn84um7vgk5jrh0k5c3ddaud3zfrgcq5tvyrr2gt6rgpfs7hrwrw
