apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 31.1.1
    releaseName: traefik
    namespace: traefik
    valuesInline:
      # Use Hetzner Load Balancer
      service:
        type: LoadBalancer
        annotations:
          load-balancer.hetzner.cloud/name: "kraleo-lb"
          load-balancer.hetzner.cloud/use-private-ip: "false"
          load-balancer.hetzner.cloud/location: "fsn1"
          load-balancer.hetzner.cloud/type: "lb11"
      
      # Enable dashboard (optional, for testing)
      ingressRoute:
        dashboard:
          enabled: true
          matchRule: Host(`traefik.localhost`)
      
      # Logs
      logs:
        general:
          level: INFO
        access:
          enabled: true
      
      # Enable Prometheus metrics
      metrics:
        prometheus:
          enabled: true
      
      # Global redirect to HTTPS
      ports:
        web:
          redirectTo:
            port: websecure
        websecure:
          tls:
            enabled: true
