apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 31.1.1
    helm:
      values: |
        # Use DaemonSet - runs on all nodes
        deployment:
          kind: DaemonSet
        
        # Use host network - direct port 80/443 access
        hostNetwork: true
        
        # Don't need a service with host network
        service:
          enabled: false
        
        ports:
          web:
            port: 8000
            hostPort: 80
          websecure:
            port: 8443
            hostPort: 443
            tls:
              enabled: true
        
        # Required for hostNetwork with DaemonSet
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 0
        
        logs:
          general:
            level: INFO
          access:
            enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
